- hosts: hacluster
  become: true
  gather_facts: no

  tasks:
    - name: copy CrystalSignalPi agents
      copy:
        src: ../agents/CrystalSignalPi
        dest: /usr/lib/ocf/resource.d/heartbeat/
        mode: '0755'
